// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vtop/vtop_errors.dart';

// These functions are ignored because they are not marked as `pub`: `access`

/// One look at the mailbox for VTOP's OTP email sent after
/// `issued_at_unix`. Errors are `ConfigurationError` with a stable code:
/// `gmail_unauthorized` (refresh the token and retry), `gmail_forbidden`,
/// `gmail_unavailable`.
Future<GmailOtpCode?> gmailFindOtp({
  required String accessToken,
  BigInt? expiresAtUnix,
  required BigInt issuedAtUnix,
  required List<String> skipMessageIds,
}) => RustLib.instance.api.crateApiEmailOtpGmailFindOtp(
  accessToken: accessToken,
  expiresAtUnix: expiresAtUnix,
  issuedAtUnix: issuedAtUnix,
  skipMessageIds: skipMessageIds,
);

/// Trashes the OTP email (or only marks it read). Best effort.
Future<void> gmailTidyUp({
  required String accessToken,
  required String messageId,
  required bool deleteAfterReading,
}) => RustLib.instance.api.crateApiEmailOtpGmailTidyUp(
  accessToken: accessToken,
  messageId: messageId,
  deleteAfterReading: deleteAfterReading,
);

/// An OTP found in Gmail.
class GmailOtpCode {
  final String code;

  /// Pass back in `skip_message_ids` if VTOP rejects the code.
  final String messageId;

  const GmailOtpCode({required this.code, required this.messageId});

  @override
  int get hashCode => code.hashCode ^ messageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GmailOtpCode &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          messageId == other.messageId;
}
