// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;
import 'vtop/types.dart';
import 'vtop/vtop_client.dart';
import 'vtop/vtop_errors.dart';

Future<VtopClient> getVtopClient({
  required String username,
  required String password,
  PersistedVtopSession? persistedSession,
}) => RustLib.instance.api.crateApiVtopGetClientGetVtopClient(
  username: username,
  password: password,
  persistedSession: persistedSession,
);

Future<void> vtopClientLogin({required VtopClient client}) =>
    RustLib.instance.api.crateApiVtopGetClientVtopClientLogin(client: client);

Future<void> vtopClientSubmitSecurityOtp({
  required VtopClient client,
  required String otpCode,
}) => RustLib.instance.api.crateApiVtopGetClientVtopClientSubmitSecurityOtp(
  client: client,
  otpCode: otpCode,
);

Future<void> vtopClientResendSecurityOtp({required VtopClient client}) =>
    RustLib.instance.api.crateApiVtopGetClientVtopClientResendSecurityOtp(
      client: client,
    );

String vtopClientRegistrationNumber({required VtopClient client}) => RustLib
    .instance
    .api
    .crateApiVtopGetClientVtopClientRegistrationNumber(client: client);

Future<SemesterData> fetchSemesters({required VtopClient client}) =>
    RustLib.instance.api.crateApiVtopGetClientFetchSemesters(client: client);

Future<AttendanceData> fetchAttendance({
  required VtopClient client,
  required String semesterId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchAttendance(
  client: client,
  semesterId: semesterId,
);

Future<BiometricData> fetchBiometricHistory({
  required VtopClient client,
  required String date,
}) => RustLib.instance.api.crateApiVtopGetClientFetchBiometricHistory(
  client: client,
  date: date,
);

Future<FullAttendanceData> fetchFullAttendance({
  required VtopClient client,
  required String semesterId,
  required String courseId,
  required String courseType,
}) => RustLib.instance.api.crateApiVtopGetClientFetchFullAttendance(
  client: client,
  semesterId: semesterId,
  courseId: courseId,
  courseType: courseType,
);

Future<TimetableData> fetchTimetable({
  required VtopClient client,
  required String semesterId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchTimetable(
  client: client,
  semesterId: semesterId,
);

Future<MarksData> fetchMarks({
  required VtopClient client,
  required String semesterId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchMarks(
  client: client,
  semesterId: semesterId,
);

Future<ExamScheduleData> fetchExamSchedule({
  required VtopClient client,
  required String semesterId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchExamSchedule(
  client: client,
  semesterId: semesterId,
);

Future<AcademicCalendarData> fetchAcademicCalendar({
  required VtopClient client,
  required String semesterId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchAcademicCalendar(
  client: client,
  semesterId: semesterId,
);

Future<GradeViewData> fetchGradeView({
  required VtopClient client,
  required String semesterId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchGradeView(
  client: client,
  semesterId: semesterId,
);

Future<GradeDetailsData> fetchGradeViewDetails({
  required VtopClient client,
  required String semesterId,
  required String courseId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchGradeViewDetails(
  client: client,
  semesterId: semesterId,
  courseId: courseId,
);

Future<GradeHistoryData> fetchGradeHistory({required VtopClient client}) =>
    RustLib.instance.api.crateApiVtopGetClientFetchGradeHistory(client: client);

Future<GeneralOutingData> fetchGeneralOuting({required VtopClient client}) =>
    RustLib.instance.api.crateApiVtopGetClientFetchGeneralOuting(
      client: client,
    );

Future<WeekendOutingData> fetchWeekendOuting({required VtopClient client}) =>
    RustLib.instance.api.crateApiVtopGetClientFetchWeekendOuting(
      client: client,
    );

/// Dates are `DD-Mon-YYYY` (`11-Oct-2026`); times are 24-hour.
Future<OutingApplyResult> applyGeneralOuting({
  required VtopClient client,
  required String place,
  required String purpose,
  required String outDate,
  required int outHour,
  required int outMinute,
  required String inDate,
  required int inHour,
  required int inMinute,
}) => RustLib.instance.api.crateApiVtopGetClientApplyGeneralOuting(
  client: client,
  place: place,
  purpose: purpose,
  outDate: outDate,
  outHour: outHour,
  outMinute: outMinute,
  inDate: inDate,
  inHour: inHour,
  inMinute: inMinute,
);

/// `place` and `time_slot` are option values from [`WeekendOutingData`].
Future<OutingApplyResult> applyWeekendOuting({
  required VtopClient client,
  required String place,
  required String purpose,
  required String date,
  required String timeSlot,
  required String contactNumber,
}) => RustLib.instance.api.crateApiVtopGetClientApplyWeekendOuting(
  client: client,
  place: place,
  purpose: purpose,
  date: date,
  timeSlot: timeSlot,
  contactNumber: contactNumber,
);

/// Cancels a general outing request while VTOP still allows it.
Future<OutingCancelResult> cancelGeneralOuting({
  required VtopClient client,
  required String leaveId,
}) => RustLib.instance.api.crateApiVtopGetClientCancelGeneralOuting(
  client: client,
  leaveId: leaveId,
);

/// Cancels a weekend outing request while VTOP still allows it.
Future<OutingCancelResult> cancelWeekendOuting({
  required VtopClient client,
  required String bookingId,
}) => RustLib.instance.api.crateApiVtopGetClientCancelWeekendOuting(
  client: client,
  bookingId: bookingId,
);

/// The PDF pass of an accepted outing.
Future<Uint8List> fetchOutingPass({
  required VtopClient client,
  required bool weekend,
  required String passId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchOutingPass(
  client: client,
  weekend: weekend,
  passId: passId,
);

/// The courses the student is registered for in [semester_id].
Future<CoursePageCourses> fetchCoursePageCourses({
  required VtopClient client,
  required String semesterId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchCoursePageCourses(
  client: client,
  semesterId: semesterId,
);

/// Every class (section) of a course, with its slot and faculty.
Future<CoursePageClasses> fetchCoursePageClasses({
  required VtopClient client,
  required String semesterId,
  required String courseId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchCoursePageClasses(
  client: client,
  semesterId: semesterId,
  courseId: courseId,
);

/// A class's lecture plan and downloads.
Future<CoursePageDetail> fetchCoursePageDetail({
  required VtopClient client,
  required String semesterId,
  required String erpId,
  required String classId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchCoursePageDetail(
  client: client,
  semesterId: semesterId,
  erpId: erpId,
  classId: classId,
);

/// The name and type of a course page download (lecture material,
/// syllabus, material bundle), so the system downloader can save it.
Future<CourseFileInfo> fetchCourseFileInfo({
  required VtopClient client,
  required String path,
}) => RustLib.instance.api.crateApiVtopGetClientFetchCourseFileInfo(
  client: client,
  path: path,
);

/// The name and type of a class's course plan (Excel).
Future<CourseFileInfo> fetchCoursePlanInfo({
  required VtopClient client,
  required String semesterId,
  required String classId,
}) => RustLib.instance.api.crateApiVtopGetClientFetchCoursePlanInfo(
  client: client,
  semesterId: semesterId,
  classId: classId,
);

Future<Uint8List> fetchCookies({required VtopClient client}) =>
    RustLib.instance.api.crateApiVtopGetClientFetchCookies(client: client);

PersistedVtopSession exportSessionSnapshot({
  required VtopClient client,
  required BigInt savedAtEpochMs,
}) => RustLib.instance.api.crateApiVtopGetClientExportSessionSnapshot(
  client: client,
  savedAtEpochMs: savedAtEpochMs,
);

/// The current session with its CSRF token and registration number, for
/// sending to a vtop-server.
SessionState exportSessionState({required VtopClient client}) => RustLib
    .instance
    .api
    .crateApiVtopGetClientExportSessionState(client: client);

/// Replaces the client's session with one logged in elsewhere (a
/// vtop-server login), including a pending OTP challenge.
void vtopClientResumeSession({
  required VtopClient client,
  required SessionState session,
}) => RustLib.instance.api.crateApiVtopGetClientVtopClientResumeSession(
  client: client,
  session: session,
);

Future<bool> fetchIsAuth({required VtopClient client}) =>
    RustLib.instance.api.crateApiVtopGetClientFetchIsAuth(client: client);
